### ISSUE TITLE
We need have ERC721 which will act as badges!

### ISSUE THREAD

**Issue by vutsalsinghal** [mickaelgermemont/AttendanceCoin#26]
I have a doubt:

Approach 1
----------------
as we had decided, whoever attends a particular class, he/she will receive a unique coin "for having attended that session". So if each coin is unique (due to being ERC21), shouldn't we have ERC20 unique to a particular class?

We can have ERC20 factory which will create unique ERC20 for each session...

**OR**

Approach 2
----------------
the ERC721 issued on a particular session will have 2 parts:
- part1 = "date of that session" 
- part2 = "Name of recipient"

**Comment by mickaelgermemont** [comment]
ERC20 is reward for contributing. fungible.
ERC721 is collectible. non fungible. unique. 

ERC20 is a pain is in the butt if you have to create a new coin each time for each class. 
also if you create a new currency for every purpose in life... something is wrong. you are making your currency harder to use because each one has a different transfer function. that means if i attend 10 meetups and i want to send those 10 different coins, i have to call 10 transfer functions of 10 different ERC20 contracts. also how do i look at my balance? i call 10 balanceOf functions...

ERC721, you attend a specific event and you get a unique badge reward for that. ERC721 is one contract that you interact with. that means if i attend 10 meetups and i want to send those 10 badges, i only intereact with 1 ERC721 contract. 

we have to define the type of assets we want to represent in the ERC721. thats for sure. we said badges. well, maybe the simplest form is, your Approach 2 ["date", "topic of the day"]. maybe other forms are "completed all level 1 dapps", "found solution to that problem", "awared best Level1 BlackDapp 2019 season 1" (maybe we would vote for that award!)...

**Comment by vutsalsinghal** [comment]
I've added a working code [here](https://github.com/vutsalsinghal/Attendance_Coin/blob/master/src/ethereum/contracts/BadgeCoin_ERC721.sol)

@mickaelgermemont need to add react code and refactor the /ethereum directory appropriately

**Comment by vutsalsinghal** [comment]
In future, we should also have a look at ERC721x by the Loom Network guys. They've done a lot of improvements/upgrades to the ERC721...
